[EMC]
VERSION = 1.1
MACHINE = Delta-robot-with-rotary-joints
DEBUG = 0

[DISPLAY]
DISPLAY = axis
MAX_LINEAR_VELOCITY = 200.0
DEFAULT_LINEAR_VELOCITY = 50.0
MAX_FEED_OVERRIDE = 1.5
PROGRAM_PREFIX = ../../../nc_files/
INTRO_GRAPHIC = linuxcnc.gif
INTRO_TIME = 5
TOOL_EDITOR = tooledit
INCREMENTS = 1 in, 0.1 in, 10 mil, 1 mil
POSITION_OFFSET = RELATIVE
POSITION_FEEDBACK = COMMANDED

[FILTER]
PROGRAM_EXTENSION = .png,.gif,.jpg Grayscale Depth Image
PROGRAM_EXTENSION = .py Python Script
png = image-to-gcode
gif = image-to-gcode
jpg = image-to-gcode
py = python3

[TASK]
TASK = milltask
CYCLE_TIME = 0.001

[RS274NGC]
PARAMETER_FILE = sim.var

[EMCMOT]
EMCMOT = motmod
BASE_PERIOD  = 0
SERVO_PERIOD = 1000000

[HAL]
HALFILE = ./Rotary_Delta.hal
HALUI = halui

[TRAJ]
COORDINATES = X Y Z
AXES = 3
LINEAR_UNITS = mm
ANGULAR_UNITS = degree
CYCLE_TIME = 0.010
# Raise trajectory planner global caps
DEFAULT_LINEAR_VELOCITY = 50.0
MAX_LINEAR_VELOCITY = 200.0
MAX_ANGULAR_VELOCITY = 360.0
SERVO_PERIOD = 1000000
# Allow the trajectory planner to ramp up faster
MAX_ACCELERATION = 2000.0

[KINS]
KINEMATICS = rotarydeltakins
JOINTS = 3

#[KINS]
#KINEMATICS = trivkins coordinates=XYZ
#JOINTS = 3

[JOINT_0]
TYPE = ANGULAR

HOME = 0
HOME_OFFSET = 0.0
HOME_SEARCH_VEL = 0.0
HOME_LATCH_VEL = 0.0
HOME_FINAL_VEL = 00.0
HOME_SEQUENCE = 0
HOME_USE_INDEX = NO	
HOME_ABSOLUTE_ENCODER = 2

MAX_VELOCITY = 360
MAX_ACCELERATION = 10000.0
MIN_LIMIT = -99999.0
MAX_LIMIT = 99999.0

FERROR = 14.0
MIN_FERROR = 4.0

[JOINT_1]
TYPE = ANGULAR

HOME = 0
HOME_OFFSET = 0.0
HOME_SEARCH_VEL = 0.0
HOME_LATCH_VEL = 0.0
HOME_FINAL_VEL = 00.0
HOME_SEQUENCE = 0
HOME_USE_INDEX = NO
HOME_ABSOLUTE_ENCODER = 2

MAX_VELOCITY = 360
MAX_ACCELERATION = 10000.0
MIN_LIMIT = -99999.0
MAX_LIMIT = 99999.0

FERROR = 14.0
MIN_FERROR = 4.0

[JOINT_2]
TYPE = ANGULAR

HOME = 0
HOME_OFFSET = 0.0
HOME_SEARCH_VEL = 0.0
HOME_LATCH_VEL = 0.0
HOME_FINAL_VEL = 00.0
HOME_SEQUENCE = 0
HOME_USE_INDEX = NO
HOME_ABSOLUTE_ENCODER = 2

MAX_VELOCITY = 360
MAX_ACCELERATION = 10000.0
MIN_LIMIT = -99999.0
MAX_LIMIT = 99999.0

FERROR = 14.0
MIN_FERROR = 4.0

[AXIS_X]
MAX_VELOCITY = 200
MAX_ACCELERATION = 2000
MIN_LIMIT = -99999.0
MAX_LIMIT = 99999.0

[AXIS_Y]
MAX_VELOCITY = 200
MAX_ACCELERATION = 2000
MIN_LIMIT = -99999.0
MAX_LIMIT = 99999.0

[AXIS_Z]
MAX_VELOCITY = 200
MAX_ACCELERATION = 2000
MIN_LIMIT = -99999.0
MAX_LIMIT = 99999.0

[EMCIO]
EMCIO = io
CYCLE_TIME = 0.1
TOOL_TABLE = sim.tbl
